product_samples = [
    "Cuốn sách này có phiên bản tiếng Anh không?",
    "Sách văn học hay",
    "Sách 'Nhà giả kim' có bản đặc biệt không?",
    "Sách 'Cuốn theo chiều gió' có phải sách gốc không?",
    "Cửa hàng có sách về nấu ăn không?",
    "Gợi ý cho tôi một vài cuốn sách văn học nước ngoài hay",
    "Cửa hàng có bán sách lịch sử Việt Nam không?",
    "Sách 'Tư duy nhanh và chậm' có phiên bản bìa cứng không?",
    "Sách 'Đắc nhân tâm' có không?",
    "Gợi ý cho tôi sách học tiếng Anh",
    "Cửa hàng có bán sách về khoa học không?",
    "Cửa hàng có sách về triết học không?",
    "Sách 'Lược sử loài người' có bản đặc biệt không?",
    "Một số tiểu thuyết hay?",
    "Sách tâm lý học của tác giả Việt Nam nào hay?",
    "Sách 'Khi hơi thở hóa thinh không' có hay không?",
    "Cửa hàng có sách về kinh tế học không?",
    "Sách của tác giả Đặng Hoàng Giang hay không?",
    "Sách 'Tôi tài giỏi bạn cũng thế' có còn hàng không?",
    "Tôi muốn đọc về vũ trụ thì nên đọc sách nào?",
    "Cửa hàng có bán sách về thiên văn học không?",
    "Một số sách về lịch sử Việt Nam hay",
    "Sách 'Hành trình về phương Đông' có hay không?",
    "Sách 'Những tấm lòng cao cả' có còn hàng không?",
    "Sách 'Cẩm nang sống sót nơi công sở' có giá bao nhiêu?",
    "Sách 'Nghệ thuật tư duy rành mạch' có bản tiếng Anh không?",
    "Sách 'Thế giới phẳng' có tái bản không?",
    "Sách 'Người đàn ông đến từ trái đất' có bản mới không?",
    "Sách 'Tư duy tích cực' có bán lẻ không?",
    "Sách 'Cuộc đời của Pi' có giá như nào?",
    "Cửa hàng có bán sách về yoga không?",
    "Sách 'Kẻ trộm sách' có bán không?",
    "Cuốn sách này có phải sách giáo khoa không?",
    "Sách 'Đường xưa mây trắng' có gì hay?",
    "Cửa hàng có sách về phong thủy không?",
    "Sách 'Nhật ký Anne Frank' có phiên bản tiếng Việt không?",
    "Sách 'Để con được ốm' có tái bản không?",
    "Sách 'Chiến tranh và hòa bình' có còn hàng không?",
    "Cửa hàng có bán sách về sức khỏe không?",
    "Sách 'Người bán hàng vĩ đại' có bản mới không?",
    "Sách 'Những người khốn khổ' có phiên bản mới không?",
    "Sách 'Trí tuệ xúc cảm' có bản đặc biệt không?",
    "Cuốn sách này có bán kèm bookmark không?",
    "Sách 'Tư duy nhanh và chậm' có hay không?",
    "Cửa hàng có sách về lập trình Python không?",
    "Sách 'Thiền sư và em bé 5 tuổi' có bản mới nhất không?",
    "Sách 'Những tấm lòng cao cả' có tác giả là ai?",
    "Cuốn sách này có phải bản dịch không?",
    "Sách 'Cuộc sống không giới hạn' có tái bản không?",
    "Sách 'Khi hơi thở hóa thinh không' có bản bìa cứng không?",
    "Cửa hàng có sách về quản lý tài chính cá nhân không?",
    "Sách 'Người đàn ông đến từ trái đất' có còn hàng không?",
    "Sách 'Tôi tài giỏi bạn cũng thế' có phiên bản mới nhất không?",
    "Cửa hàng có sách về khoa học không?",
    "Cuốn sách này có tặng kèm không?",
    "Sách 'Chiến tranh và hòa bình' có bán ở đâu?",
    "Sách 'Nhật ký Anne Frank' có bản mới không?",
    "Sách 'Giáo dục là một nghệ thuật' có tái bản không?",
    "Cửa hàng có bán sách về kinh doanh không?",
    "Sách 'Người bán hàng vĩ đại nhất thế giới' có còn hàng không?",
]

chat_samples = [
     "Thời tiết hôm nay như thế nào?",
    "Ngoài trời nóng bao nhiêu?",
    "Ngày mai có mưa không?",
    "Nhiệt độ hiện tại là bao nhiêu?",
    "Bạn có thể cho tôi biết điều kiện thời tiết hiện tại không?",
    "Cuối tuần này có nắng không?",
    "Nhiệt độ hôm qua là bao nhiêu?",
    "Đêm nay trời sẽ lạnh đến mức nào?",
    "Ai là tổng thống đầu tiên của Hoa Kỳ?",
    "Chiến tranh thế giới thứ hai kết thúc vào năm nào?",
    "Bạn có thể kể cho tôi về lịch sử của internet không?",
    "Tháp Eiffel được xây dựng vào năm nào?",
    "Ai đã phát minh ra điện thoại?",
    "Tên của bạn là gì?",
    "Bạn có tên không?",
    "Tôi nên gọi bạn là gì?",
    "Ai đã tạo ra bạn?",
    "Bạn bao nhiêu tuổi?",
    "Bạn có thể kể cho tôi một sự thật thú vị không?",
    "Bạn có biết bất kỳ câu đố thú vị nào không?",
    "Màu sắc yêu thích của bạn là gì?",
    "Bộ phim yêu thích của bạn là gì?",
    "Bạn có sở thích nào không?",
    "Ý nghĩa của cuộc sống là gì?",
    "Bạn có thể kể cho tôi một câu chuyện cười không?",
    "Thủ đô của Pháp là gì?",
    "Dân số thế giới là bao nhiêu?",
    "Có bao nhiêu châu lục?",
    "Ai đã viết 'Giết con chim nhại'?",
    "Bạn có thể cho tôi một câu nói của Albert Einstein không?",
     "Tôi thích đọc sách"
]